deploy:
  provider: s3
  access_key_id: AKIAJ7NZ4KULBFHSNZ5Q
  secret_access_key:
    secure: AXjZuxlVgZWAtvFStp7/4u0Ru1grTYAiikhu3Nadz35/AgmsGk0qFDzPZyaz/X5ox0Yf8bmdMLdWVj60K8IkRi4LJ3r6tqFJE5yLwDsT1UFkpWhJCuJXFAifOORf3VwTYRKPyP6NSttEOuPvMppV7LYKrB9QDaWpjJjoPaeJ+T0qbRJP9rDADwiPSZ/xWsTQEnYM0KgWD0SZHELwDuNrG2xFofG05EaIcl41cAAIt4n4WnyQ9c3iGHzFWHvrhlXcyv6JpxgL+vQIAm43kwdGrnQ9yvm9cNn0pN53UvFnawYyBkS6z6MZssIrzi8IFl+mHdCSBKdQbqnpY6zlP95hu9qSvvY4GAZiFCpDXX2/075P+4kAusnkOs7Z7IUWslDqXRFEyQwyvD8KRdUxdAJBM+xQZjN2qJ4gJbadbalncRU6yAbnZr8aBkaFJ9tND/gyDRLOtJN90G5hrWacxl9JnkH7UAhX4q0PJdaHk/hORjLaJ3BWFGgcmMkgXyk8O1nzVy7j86KoGOEx9tQ9n3nqOSeROAxdmYM6m8QezoY/nfNCSB2Vs+tw0hBADYGorBBs2ou7QXt+Hf69CfYpds44gRVLaCG6FISPTrZpGHj9Y94BSwBgwWgfa8+7UcKGYSDTFVY5aobNRxFdI2jabfcXjF6R5UW2kvNJ8NWMSmgDXnE=
  bucket: owen.cafe
  on:
    repo: 414owen/personal-site

language: c
script:
  - echo "hello"
